# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5eeed0af81ba06de062b4f75034d44462eafb9443cbe222ecac950df9b7fcd6f1c8f75e3ed9dd3714157efa8107951c956d52af23ed7c267aa311884ce0f7a01

test:
  secret_key_base: 28e233e135c0a0a4885e4fd18a6764b72e4cd536070e8ef416c725d2a0fa9a92dda1f8839b9dd2969d8d94bb4cb0f409f1e1474b581415599713e93927a85d5e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
